services:
  java:
    build: .
    container_name: ${NAME:?}-java
    command: ${NAME:?}-${VERSION:?}-jar-with-dependencies.jar
    environment:
      - POSTGRES_SERVICE=db:5432
      - POSTGRES_DB=${POSTGRES_DB:?}
      - POSTGRES_USER=${POSTGRES_USER:?}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?}
    depends_on:
      - db

  db:
    image: postgres:9.3-alpine
    container_name: ${NAME:?}-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB:?}
      - POSTGRES_USER=${POSTGRES_USER:?}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    name: ${NAME:?}-data
    external: true
