services:
  java:
    build: .
    container_name: ejercicio-java
    command: ejercicio-1.0-SNAPSHOT-jar-with-dependencies.jar
    environment:
      - POSTGRES_SERVICE=db:5432
      - POSTGRES_DB=${POSTGRES_DB:?}
      - POSTGRES_USER=${POSTGRES_USER:?}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?}
    depends_on:
      - db

  db:
    image: postgres:9.3-alpine
    container_name: ejercicio-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB:?}
      - POSTGRES_USER=${POSTGRES_USER:?}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?}
    volumes:
      - ejercicio-data:/var/lib/postgresql/data

volumes:
  ejercicio-data:
    external: true
