services:
  java:
    build:
      context: .
      dockerfile: Dockerfile
      target: java
    container_name: pepita-java
    ports:
      - ${PORT:?}:${PORT:?}
    environment:
      - PORT=${PORT:?}
      - DB_URL=jdbc:postgresql://db:5432/${DB_NAME:?}
      - DB_USERNAME=${DB_USERNAME:?}
      - DB_PASSWORD=${DB_PASSWORD:?}
      - DB_DRIVER=org.postgresql.Driver
      - DB_DIALECT=org.hibernate.dialect.PostgresPlusDialect
    depends_on:
      - db

  cron:
    build:
      context: .
      dockerfile: Dockerfile
      target: cron
    container_name: pepita-cron
    env_file:
      - .env
    environment:
      - POSTGRES_SERVICE=db:5432
    depends_on:
      - db

  db:
    image: postgres:9.3-alpine
    container_name: pepita-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DB_NAME:?}
      - POSTGRES_USER=${DB_USERNAME:?}
      - POSTGRES_PASSWORD=${DB_PASSWORD:?}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    name: pepita-data
    external: true
