services:
  java:
    build:
      context: .
      dockerfile: Dockerfile
      target: java
    container_name: pepita-java
    ports:
      - ${PORT:?}:${PORT:?}
    env_file:
      - .env
    environment:
      - POSTGRES_SERVICE=db:5432
    depends_on:
      - db

  cron:
    build:
      context: .
      dockerfile: Dockerfile
      target: cron
    container_name: pepita-cron
    env_file:
      - .env
    environment:
      - POSTGRES_SERVICE=db:5432
    depends_on:
      - db

  db:
    image: postgres:9.3-alpine
    container_name: pepita-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB:?}
      - POSTGRES_USER=${POSTGRES_USER:?}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    name: pepita-data
    external: true
